# Generated by Django 4.0.2 on 2022-08-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Add_Flat', '0002_alter_add_flat_flat_image'),
        ('App_Login', '0004_alter_user_registration_nid_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_info', to='App_Add_Flat.add_flat')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_info', to='App_Login.user_registration')),
            ],
        ),
    ]
