# Generated by Django 4.0.2 on 2022-09-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Add_Flat', '0003_alter_add_flat_bedroom_alter_add_flat_floor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_card_expire_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cvv_number', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_card_info_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_info_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('billing_time', models.TimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[(1, 'Bank'), (2, 'Credit Card'), (3, 'Bkash'), (4, 'Nagad')], max_length=20)),
                ('billing_amount', models.IntegerField()),
                ('billing_status', models.CharField(choices=[('Pending', 'Pending'), ('UnPaid', 'UnPaid'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('billing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_flat', to='App_Add_Flat.add_flat')),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_swift_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_info_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
