# Generated by Django 4.0.2 on 2022-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bank'), (2, 'Credit Card'), (3, 'Bkash'), (4, 'Nagad')]),
        ),
    ]
