# Generated by Django 4.0.2 on 2022-09-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Add_Flat', '0003_alter_add_flat_bedroom_alter_add_flat_floor_and_more'),
        ('App_Payment', '0002_alter_billinginfo_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('UnPaid', 'UnPaid'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_time',
            field=models.TimeField(default=False),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_flat', to='App_Add_Flat.add_flat'),
        ),
    ]
