# Generated by Django 4.0.2 on 2022-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0003_alter_billinginfo_billing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_time',
            field=models.TimeField(),
        ),
    ]
