# Generated by Django 4.0.2 on 2022-09-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0004_alter_billinginfo_billing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='billing_time',
        ),
    ]
