# Generated by Django 4.0.2 on 2022-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay_Feedback',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='address',
        ),
        migrations.AddField(
            model_name='feedback',
            name='replay_feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='flat_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='house_name',
            field=models.CharField(max_length=200),
        ),
    ]
