# Generated by Django 4.0.2 on 2022-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Add_Flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_flat',
            name='Flat_image',
            field=models.ImageField(blank=True, null=True, upload_to='flat_pics'),
        ),
    ]
