# Generated by Django 4.0.2 on 2022-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Add_Flat', '0002_alter_add_flat_flat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_flat',
            name='Bedroom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='add_flat',
            name='Floor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='add_flat',
            name='Number_of_balcony',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='add_flat',
            name='Number_of_bath',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
